import type { Job, Client, Quote, Invoice, Certificate, DashboardStats, Activity } from '@/types'

export const DEMO_CLIENTS: Client[] = [
  {
    id: 'c1',
    name: 'Sarah Mitchell',
    email: 'sarah.mitchell@email.co.uk',
    phone: '07712 345678',
    address: '14 Maple Avenue, Birmingham',
    postcode: 'B15 2TH',
    notes: 'Prefers morning appointments',
    created_at: '2024-01-15T09:00:00Z',
    job_count: 3,
    total_billed: 2450,
  },
  {
    id: 'c2',
    name: 'James & Patricia Holden',
    email: 'jholden@gmail.com',
    phone: '07823 456789',
    address: '7 Victoria Street, Manchester',
    postcode: 'M1 4BU',
    created_at: '2024-02-20T10:00:00Z',
    job_count: 5,
    total_billed: 8750,
  },
  {
    id: 'c3',
    name: 'Green Valley Lettings Ltd',
    email: 'maintenance@greenvalley.co.uk',
    phone: '0121 567 8900',
    address: '25 Commercial Road, Birmingham',
    postcode: 'B1 1AA',
    notes: 'Commercial account. PO required for all work.',
    created_at: '2024-03-01T08:00:00Z',
    job_count: 12,
    total_billed: 15600,
  },
  {
    id: 'c4',
    name: 'Tom Blackwell',
    email: 'tomblackwell@hotmail.com',
    phone: '07934 567890',
    address: '3 Oak Close, Leeds',
    postcode: 'LS1 5PQ',
    created_at: '2024-04-10T11:00:00Z',
    job_count: 1,
    total_billed: 850,
  },
]

export const DEMO_JOBS: Job[] = [
  {
    id: 'j1',
    title: 'Full rewire — 3 bed semi',
    client_id: 'c2',
    client_name: 'James & Patricia Holden',
    client_address: '7 Victoria Street, Manchester, M1 4BU',
    status: 'in_progress',
    priority: 'high',
    job_type: 'electrical',
    jurisdiction: 'england',
    description: 'Complete rewire of 3-bedroom semi-detached. New consumer unit, all circuits, smoke alarms.',
    scheduled_date: '2024-07-15',
    start_time: '08:00',
    estimated_hours: 16,
    actual_hours: 12,
    hourly_rate: 55,
    materials_cost: 650,
    total_cost: 1530,
    created_at: '2024-07-10T09:00:00Z',
    updated_at: '2024-07-15T10:00:00Z',
    tags: ['rewire', 'domestic', '18th-edition'],
  },
  {
    id: 'j2',
    title: 'Bathroom circuit replacement',
    client_id: 'c1',
    client_name: 'Sarah Mitchell',
    client_address: '14 Maple Avenue, Birmingham, B15 2TH',
    status: 'scheduled',
    priority: 'medium',
    job_type: 'electrical',
    jurisdiction: 'england',
    description: 'Replace bathroom shower circuit, fit new 45A DP isolator, test and inspect.',
    scheduled_date: '2024-07-18',
    start_time: '09:00',
    estimated_hours: 4,
    hourly_rate: 55,
    materials_cost: 75,
    total_cost: 295,
    created_at: '2024-07-12T14:00:00Z',
    updated_at: '2024-07-12T14:00:00Z',
    tags: ['bathroom', 'shower'],
  },
  {
    id: 'j3',
    title: 'Consumer unit upgrade',
    client_id: 'c3',
    client_name: 'Green Valley Lettings Ltd',
    client_address: '12 Tenant Street, Birmingham, B2 3CD',
    status: 'completed',
    priority: 'urgent',
    job_type: 'electrical',
    jurisdiction: 'england',
    description: 'Replace old fuse board with new 18th edition CU. Full inspection.',
    scheduled_date: '2024-07-10',
    estimated_hours: 6,
    actual_hours: 7,
    hourly_rate: 55,
    materials_cost: 280,
    total_cost: 665,
    created_at: '2024-07-08T10:00:00Z',
    updated_at: '2024-07-10T16:00:00Z',
    tags: ['CU-upgrade', 'landlord'],
  },
  {
    id: 'j4',
    title: 'EV charger installation',
    client_id: 'c4',
    client_name: 'Tom Blackwell',
    client_address: '3 Oak Close, Leeds, LS1 5PQ',
    status: 'invoiced',
    priority: 'medium',
    job_type: 'electrical',
    jurisdiction: 'england',
    description: 'Supply and install 7kW EV home charger. Dedicated circuit from CU.',
    scheduled_date: '2024-07-05',
    estimated_hours: 5,
    actual_hours: 5,
    hourly_rate: 55,
    materials_cost: 450,
    total_cost: 725,
    created_at: '2024-07-01T09:00:00Z',
    updated_at: '2024-07-05T15:00:00Z',
    tags: ['EV', 'OZEV'],
  },
]

export const DEMO_QUOTES: Quote[] = [
  {
    id: 'q1',
    quote_number: 'QT-2024-0041',
    client_id: 'c1',
    client_name: 'Sarah Mitchell',
    status: 'sent',
    items: [
      { id: 'qi1', description: 'Bathroom shower circuit replacement', quantity: 1, unit_price: 220, total: 220 },
      { id: 'qi2', description: '45A DP isolator switch supply & fit', quantity: 1, unit_price: 75, total: 75 },
      { id: 'qi3', description: 'Inspection & test + EIC', quantity: 1, unit_price: 95, total: 95 },
    ],
    subtotal: 390,
    vat_rate: 20,
    vat_amount: 78,
    total: 468,
    valid_until: '2024-08-12',
    created_at: '2024-07-12T14:30:00Z',
  },
  {
    id: 'q2',
    quote_number: 'QT-2024-0042',
    client_id: 'c3',
    client_name: 'Green Valley Lettings Ltd',
    status: 'accepted',
    items: [
      { id: 'qi4', description: 'EICR inspection — 3 circuits', quantity: 1, unit_price: 150, total: 150 },
      { id: 'qi5', description: 'C2 remedial works (allowance)', quantity: 1, unit_price: 200, total: 200 },
    ],
    subtotal: 350,
    vat_rate: 20,
    vat_amount: 70,
    total: 420,
    valid_until: '2024-08-01',
    created_at: '2024-07-13T09:00:00Z',
  },
  {
    id: 'q3',
    quote_number: 'QT-2024-0039',
    client_id: 'c2',
    client_name: 'James & Patricia Holden',
    status: 'draft',
    items: [
      { id: 'qi6', description: 'Full rewire — 3 bed semi', quantity: 1, unit_price: 2800, total: 2800 },
      { id: 'qi7', description: 'New consumer unit (20-way)', quantity: 1, unit_price: 350, total: 350 },
      { id: 'qi8', description: 'Smoke/CO alarms x4', quantity: 4, unit_price: 45, total: 180 },
    ],
    subtotal: 3330,
    vat_rate: 20,
    vat_amount: 666,
    total: 3996,
    valid_until: '2024-08-10',
    created_at: '2024-07-11T10:00:00Z',
  },
]

export const DEMO_INVOICES: Invoice[] = [
  {
    id: 'inv1',
    invoice_number: 'INV-2024-0087',
    client_id: 'c4',
    client_name: 'Tom Blackwell',
    job_id: 'j4',
    status: 'overdue',
    items: [
      { id: 'ii1', description: 'EV charger installation — 7kW', quantity: 1, unit_price: 725, total: 725 },
    ],
    subtotal: 725,
    vat_rate: 20,
    vat_amount: 145,
    total: 870,
    amount_paid: 0,
    due_date: '2024-07-05',
    created_at: '2024-07-05T16:00:00Z',
  },
  {
    id: 'inv2',
    invoice_number: 'INV-2024-0088',
    client_id: 'c3',
    client_name: 'Green Valley Lettings Ltd',
    job_id: 'j3',
    status: 'paid',
    items: [
      { id: 'ii2', description: 'Consumer unit upgrade', quantity: 1, unit_price: 665, total: 665 },
    ],
    subtotal: 665,
    vat_rate: 20,
    vat_amount: 133,
    total: 798,
    amount_paid: 798,
    due_date: '2024-07-24',
    created_at: '2024-07-10T17:00:00Z',
  },
  {
    id: 'inv3',
    invoice_number: 'INV-2024-0086',
    client_id: 'c1',
    client_name: 'Sarah Mitchell',
    status: 'sent',
    items: [
      { id: 'ii3', description: 'Outdoor socket installation', quantity: 2, unit_price: 120, total: 240 },
    ],
    subtotal: 240,
    vat_rate: 20,
    vat_amount: 48,
    total: 288,
    amount_paid: 0,
    due_date: '2024-07-28',
    created_at: '2024-07-08T11:00:00Z',
  },
]

export const DEMO_CERTIFICATES: Certificate[] = [
  {
    id: 'cert1',
    cert_type: 'EIC',
    status: 'issued',
    client_id: 'c4',
    client_name: 'Tom Blackwell',
    job_id: 'j4',
    property_address: '3 Oak Close, Leeds, LS1 5PQ',
    jurisdiction: 'england',
    issued_date: '2024-07-05',
    cert_number: 'EIC-2024-0102',
    ai_assisted: false,
    created_at: '2024-07-05T15:30:00Z',
  },
  {
    id: 'cert2',
    cert_type: 'EICR',
    status: 'draft',
    client_id: 'c3',
    client_name: 'Green Valley Lettings Ltd',
    property_address: '12 Tenant Street, Birmingham, B2 3CD',
    jurisdiction: 'england',
    ai_assisted: true,
    notes: 'AI assisted with observations wording — requires certified review before issue',
    created_at: '2024-07-13T10:00:00Z',
  },
  {
    id: 'cert3',
    cert_type: 'risk_assessment',
    status: 'reviewed',
    client_id: 'c2',
    client_name: 'James & Patricia Holden',
    job_id: 'j1',
    property_address: '7 Victoria Street, Manchester, M1 4BU',
    jurisdiction: 'england',
    issued_date: '2024-07-14',
    cert_number: 'RA-2024-0055',
    ai_assisted: true,
    created_at: '2024-07-14T08:00:00Z',
  },
]

export const DEMO_STATS: DashboardStats = {
  todaysJobs: 2,
  overdueInvoices: 1,
  pendingQuotes: 2,
  expiringCerts: 1,
  totalRevenue: 24750,
  outstandingAmount: 1158,
}

export const DEMO_ACTIVITIES: Activity[] = [
  {
    id: 'a1',
    type: 'job',
    title: 'Job started',
    description: 'Full rewire — James & Patricia Holden',
    timestamp: '2024-07-15T08:15:00Z',
    icon: 'Zap',
  },
  {
    id: 'a2',
    type: 'invoice',
    title: 'Invoice paid',
    description: 'INV-2024-0088 — Green Valley Lettings (£798)',
    timestamp: '2024-07-14T14:30:00Z',
    icon: 'CheckCircle',
  },
  {
    id: 'a3',
    type: 'quote',
    title: 'Quote accepted',
    description: 'QT-2024-0042 — Green Valley Lettings (£420)',
    timestamp: '2024-07-14T11:00:00Z',
    icon: 'FileCheck',
  },
  {
    id: 'a4',
    type: 'certificate',
    title: 'Certificate issued',
    description: 'EIC-2024-0102 — Tom Blackwell EV install',
    timestamp: '2024-07-13T16:45:00Z',
    icon: 'Award',
  },
  {
    id: 'a5',
    type: 'client',
    title: 'New client',
    description: 'Tom Blackwell added to CRM',
    timestamp: '2024-07-10T09:00:00Z',
    icon: 'UserPlus',
  },
]
